### PR TITLE
Website playbook: use include

### PR DESCRIPTION
**Pull request by sbesson**
Implements the suggestion made in https://github.com/openmicroscopy/infrastructure/pull/106#issuecomment-242857664

```
$ ansible-playbook -i inventory/openstack.py -e vm_key_name=seb-dundee -e vm_name=www-dev uod-web.yml -t jekyll_deploy

PLAY [OME Website Setup] *******************************************************

TASK [setup] *******************************************************************
ok: [9024a592-1b6c-446c-abe6-fbd6551dc693]

TASK [Create www-dev.openmicroscopy.org root directory] ************************
ok: [9024a592-1b6c-446c-abe6-fbd6551dc693]

TASK [Clone www-dev.openmicroscopy.org source code repository] *****************
ok: [9024a592-1b6c-446c-abe6-fbd6551dc693]

TASK [Build the website using Jekyll] ******************************************
changed: [9024a592-1b6c-446c-abe6-fbd6551dc693]

TASK [Update Nginx configuration for www-dev.openmicroscopy.org] ***************
ok: [9024a592-1b6c-446c-abe6-fbd6551dc693]

PLAY RECAP *********************************************************************
9024a592-1b6c-446c-abe6-fbd6551dc693 : ok=5    changed=1    unreachable=0    failed=0   

```

### CODE REVIEW

**Comment by joshmoore** [comment]
The files look good. I'm a bit confused about the "jekyll_deploy" tag. Is it (or "quickdeploy") still needed?

**Comment by sbesson** [comment]
It is not necessary but allows to run the second playbook alone if we want to allow quick deployment. I literally followed the example in http://goodcode.io/articles/ansible-tips/ but happy to remove for now. Also I am working on another commit to move the included files under a subdirectory following the `idrsystems-playbooks` example. We can wait until this is complete or get this together if you prefer.

**Comment by sbesson** [comment]
Last commit should also fix Travis (which is not included in this repo). I had to include the nginx role in the `jekyll-deploy` subplaybook to let the handler work.

With this the following is sufficient to only rebuild and redeploy the Jekyll-based website, so it might be we do not need the tags at all?

```
ansible-playbook -i inventory/openstack.py -e vm_name=www-dev -e vm_key_name=seb-dundee jekyll-playbooks/jekyll-deploy.yml
```

**Comment by joshmoore** [comment]
Nice. Merging. I'll test via my PR for demonstration tomorrow.

**Pull request merged**
